### ISSUE TITLE
Get OpenAIRE harvesting working

### ISSUE THREAD

**Issue by cyplas** [clarinsi/clarin-dspace#13]
If I recall correctly, Jozef suggested on his last visit that we register and integrate with OpenAIRE . I tried OpenAIRE's compatibility test at the time, which yielded mixed results, and this issue went implicitly on the backlog. Reviving it here.

* steps for joining openaire: https://www.openaire.eu/validator/help.action
* registering our repository: http://www.opendoar.org/suggest.php
* guidelines for data archives: https://guidelines.openaire.eu/en/latest/data/index.html
* compatibility tester: https://www.openaire.eu/validator
* our exposed openaire sets: http://www.clarin.si/repository/oai/openaire_data?verb=ListRecords&metadataPrefix=oai_datacite&set=openaire_data
* curation test: https://www.clarin.si/repository/xmlui/admin/curate (Check OpenAIRE items)
* related issues: length of local.sponsor (#6), euFunds/dc.relation mismatch (#7)

The compatibility tester website doesn't seem to be working at the moment, I hope this is just a temporary problem. I think rerunning those tests and inspecting the results is the next step.

**Comment by cyplas** [comment]
The compatibility tester worked for me now, and I tested it over our http://www.clarin.si/repository/oai/openaire_data. The test results are here (registration necessary): https://www.openaire.eu/validator/prepareSummary.action?jobId=10510. Half the item pass OK, half get warnings, and one gets an error. But I studied the guidelines for data archives, and the warnings are, I think, just about missing optional elements. And I asked openaire about the surprising error, and they said that it's a bug in their validator. In short, it looks like the issues from #6 and #7 are not showstoppers (although I still intend to get to the bottom of them), so we could probably already try to get registered etc.

For registration in opendoar, this link (https://www.openaire.eu/validator/populateDoarList.action?mode=re3data: then click on the Register link next to clarin.si) is better than the one I posted before, because it pre-fills some data from re3data, where it seems we're already registered. @et, could you please fill this in for us?

**Comment by TomazErjavec** [comment]
@cyplas, tried to register CLARIN.SI with opendoar as you suggest above, but:

> The compatibility test of your data repository on repo: http://www.clarin.si/repository/oai/request and set: none was unsuccessful and the join process has failed. 
Your Scores: 0/100 and 0/100 . Score required to pass: >50 
 Please review the results and correct any errors: 
https://www.openaire.eu/validator/prepareSummary.action?jobId=10515

Could be I should have entered the validation set for OpenAIRE records, but I have no idea how to do this. Help?

**Comment by cyplas** [comment]
Try using the URL I mentioned for the validation tests: http://www.clarin.si/repository/oai/openaire_data. (This is where the repository is exposed in openaire-friendly format.)

**Comment by TomazErjavec** [comment]
Thanks. We took this forward off-line, hopefully it will be ok once OpenAIRE update their listing and get rid of their bugs. And then we can close this issue.

**Comment by cyplas** [comment]
The URL given us by openaire (https://www.openaire.eu/search/dataprovider?datasourceId=re3data_____::fe0d76581a60e1287a93e2ed2cb29339) now shows our repository and 26 entries. Is this correct? If so, I suggest we close this issue. The openaire compatibility tests only fail on optional components/attributes and an (acknowledged) failure in openaire's testing code, and other problems fall under other issues (e.g., #6).

**Comment by TomazErjavec** [comment]
26 sounds about right. However, I see another problem, the institutions and country of CLARIN.SI@OpenAire, https://www.openaire.eu/search/data-providers#text:slovenian%20clarin 
shows "Czech Republic, Slovenia, European Union" + "Charles University in Prague, Faculty of Mathematics and Physics, Institute of Formal and Applied Linguistics, CLARIN.SI, Ministry of Education, Science and Sport, Jožef Stefan Institute, CLARIN ERIC ".

I'm not sure where the Czech info comes from, but I think not from RE3DATA, at least I can't find it there.
Thoughts, or, even better, solutions?

**Comment by cyplas** [comment]
They've fixed this now, upon request.
