### ISSUE TITLE
Error with login via clarin.eu IdP

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/clarin-dspace#14]
Currently if you try to log in via "Clarin.eu website account" you get an error message as below.
Maybe something to do with CLARIN.EU IdP changing their site some months ago?

```
opensaml::saml2md::MetadataException

The system encountered an error at Tue Aug 22 10:48:40 2017

To report this problem, please contact the site administrator at support@ijs.si.

Please include the following message in any email:

opensaml::saml2md::MetadataException at (https://www.clarin.si/Shibboleth.sso/Login)

Unable to locate metadata for identity provider (https://idp.clarin.eu)
```

**Comment by cyplas** [comment]
Yes, we have the clarin IdP hard-coded in aai.js, because (I think) we wanted to set the ranking of clarin.eu in the list. I've now fixed this (idp.clarin.eu -> idm.clarin.eu) and successfully tested it with my clarin.eu credentials.
