### ISSUE TITLE
Adjust handling of multiple authors in refbox

### ISSUE THREAD

**Issue by cyplas** [clarinsi/clarin-dspace#15]
Lindat's approach to showing the number of authors in the refbox ("Please use the following text to cite ...") is "up to 3" (https://github.com/ufal/clarin-dspace/issues/602) and adding "et al." if necessary, so:

- 1: A
- 2: A and B
- 3: A; B and C
- 4+: A; B; C; et al.

But it would probably be more standard to follow the "First text citation" column in the APA table here (http://blog.apastyle.org/apastyle/2011/11/the-proper-use-of-et-al-in-apa-style.html), so:

- 1: A
- 2: A and B
- 3: A; B and C
- 4: A; B; C and D
- 5: A; B; C; D and E
- 6+: A; et al.

@TomazErjavec: I've adapted it to work this way on fado; what do you think (compared to fido)?

**Comment by TomazErjavec** [comment]
Thanks, I agree, i.e. I really don't like the current LINDAT style of citation, nobody uses it elsewhere.
I had a look at current fado, and I like it.

**Comment by cyplas** [comment]
Ok, I've now deployed this on fido too.
