### ISSUE TITLE
sp.clarin.si warnings in ERIC's master_qa_report.html

### ISSUE THREAD

**Issue by cyplas** [clarinsi/clarin-dspace#22]
There are 3 sp.clarin.si warnings in CLARIN ERIC's https://clarin-eric.github.io/SPF-SPs-metadata/page/master_qa_report.html. They aren't critical, but do not come up for LINDAT, so seem specific to our installation.

**Comment by cyplas** [comment]
> There are 3 sp.clarin.si warnings in CLARIN ERIC's https://clarin-eric.github.io/SPF-SPs-metadata/page/master_qa_report.html. 

In order to eliminate these warnings, we need to shorten the descriptions to under 100 characters (although we are far from the only ones with this error). It looks like this should be done here (https://github.com/clarin-eric/SPF-SPs-metadata/blob/master/clarin-sp-metadata.xml#L7593), followed by a pull request (https://github.com/clarin-eric/SPF-SPs-metadata). Do we need to be worried about where these get propogated? Anyway, Tomaz, if you provide me with shorter descriptions (for English, German, Slovene, French), I can deal with the pull request. Well, actually only the English and German generate this error (no idea why).

Even if we don't shorten, we could at least fix the French, at least the typo ("del l'infrastructure" should be "de l'infrastructure").

**Comment by TomazErjavec** [comment]
Shortened:

```
<mdui:DisplayName
    xml:lang="en">CLARIN.SI Repository</mdui:DisplayName>
<mdui:Description
    xml:lang="en">CLARIN.SI: Digital repository and services of the Slovenian CLARIN RI at the Jožef Stefan Institute</mdui:Description>
<mdui:DisplayName
    xml:lang="sl">Repozitorij CLARIN.SI</mdui:DisplayName>
<mdui:Description
    xml:lang="sl">CLARIN.SI: Digitalni repozitorij in storitve slovenske RI CLARIN na Institutu »Jožef Stefan«</mdui:Description>
<mdui:DisplayName
    xml:lang="fr">CLARIN.SI Repositoire</mdui:DisplayName>
<mdui:Description
    xml:lang="fr">CLARIN.SI: Repositoire et des services CLARIN, Institut Jožef Stefan</mdui:Description>
<mdui:DisplayName
    xml:lang="de">CLARIN.SI Dienste</mdui:DisplayName>
<mdui:Description
    xml:lang="de">CLARIN.SI: digitale Langzeitarchiv CLARIN</mdui:Description>
```

I've no idea if this is correct.. Jona wrote it a long time ago, but don't want to bother him..

**Comment by cyplas** [comment]
Ok, but 2 things: 
1. I will drop the "des" from the French "Repositoire et des services" (I don't think it's right here)
2. Why no mention of IJS in (only) German?

**Comment by TomazErjavec** [comment]
>  I will drop the "des" from the French "Repositoire et des services" (I don't think it's right here)

Sure, I have no idea what is right and what is wrong (at least in French:)

>    Why no mention of IJS in (only) German?

Simply because it wasn't mentioned before, and I am not sure how to do it in proper German...
If you know, please do, although maybe this would be ok:

```
<mdui:Description
    xml:lang="de">CLARIN.SI: digitale Langzeitarchiv CLARIN, Institut Jožef Stefan</mdui:Description>
```

Or should it be "das Institut"? Hm.

**Comment by cyplas** [comment]
Ok, I adjusted the French and left your German and pull requested. They have accepted it and the clarin.si errors no longer show up at https://clarin-eric.github.io/SPF-SPs-metadata/page/master_qa_report.html. :)

I've also updated our local SP settings to match (<mdui:Description> in /etc/shibboleth/md_template.xml).
