### ISSUE TITLE
Translation the newly added message keys

### ISSUE THREAD

**Issue by cyplas** [clarinsi/clarin-dspace#24]
See 5d98b7d for the set of new keys to be translated (some of these (login-*) are actually not new, but we didn't have them in our message files).

Note that, since https://github.com/ufal/clarin-dspace/issues/662 was added in 2017.04, the JS messages are now all stored in a dedicated JS file, analogous to the XML file. 

The keys that I've now added (both XML and JS) are precisely the ones that the cs message files contain which the sl message files lacked, as identified with `python utilities/project_helpers/scripts/check-message-translations.py cs sl` (see my https://github.com/ufal/clarin-dspace/wiki/Language-localisation for rough documentation).

**Comment by TomazErjavec** [comment]
This has been translated and is mounted on CLARIN.SI repo.
