### ISSUE TITLE
Add ISO code for Montenegrin

### ISSUE THREAD

**Issue by cyplas** [clarinsi/clarin-dspace#26]
The ISO language entry for Montenegrin ("cnr: Montenegrin") isn't in dspace yet, as it was only approved in 2017. It needs to be added.

**Comment by cyplas** [comment]
I think I've now added support for this on fado (f74aa9ca0a05a3b008d0692c29a1fc0bc96ecbc4). For example, https://beta.clarin.si/repository/xmlui/handle/11356/1059. 
@TomazErjavec: could you verify?

**Comment by TomazErjavec** [comment]
Verified, it works!
Awaiting its release on fido.
