### ISSUE TITLE
Old versions of resource not clicklabe in "Other versions" list

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/clarin-dspace#27]
The new version of LINDAT has, on the landing page of an item, the option "Other versions" which gives you a list of previous version of a resource. These versions are at the UFAL installation clickable, at least for some (but not all??) instances, cf. http://hdl.handle.net/11234/1-2515 where you can click on e.g. UD 1.2, but not on UD 2.0. This is a bit of a mystery..
However, at our repository, you cannot click on any previous version, cf. the previous version list of http://hdl.handle.net/11356/1181 (some previous version, like 2.0, have local.hidden = hidden, but not all, like 1.4, in case that is relevant).
It would be of course very useful, if one could click on a previous version.

**Comment by cyplas** [comment]
Looking into this issue now, but it seems to have been fixed in the meantime, perhaps in a release upgraded to. Looking at the example you gave (http://hdl.handle.net/11356/1181), all other versions are clickable. @TomazErjavec Could you please verify and close, if appropriate?

**Comment by TomazErjavec** [comment]
> @TomazErjavec Could you please verify and close, if appropriate?

Alas, I can't confirm that it works on Firefox. On http://hdl.handle.net/11356/1181 there are 4 other versions of the resource. In Chrome I can click on all of them, but in Firefox only one (v 2.0) is clickable. Even worse, the bottom-most version (1.3) looks like it is clickable, but the link is actually to the CLARIN B Centre link, so something *under* the pop-up window.

So, my impression is that nothing has actually changed, just that we didn't notice before that some can be clicked (but others not). I should stress that everything is ok in Chrome, problems are in Firefox.

**Comment by cyplas** [comment]
> everything is ok in Chrome, problems are in Firefox.

Aha, this is a known problem: https://github.com/ufal/clarin-dspace/issues/874

**Comment by TomazErjavec** [comment]
Even though ufal#874 is not closed, I can report that this works fine now under Firefox. Closing.
