### ISSUE TITLE
Incorporate full Slovene message translations and check for completeness

### ISSUE THREAD

**Issue by cyplas** [clarinsi/clarin-dspace#32]

**Comment by cyplas** [comment]
@TomazErjavec There are a few issues with the message translation file you provided me with:

1. The file includes only the keys from the main English message file, not the 3 others (SwordClient, Discovery, XMLWorkflow).
2. Many of the translated keys had already been translated before, often (quite) differently. Should I clobber all the old translations with the new ones? In addition to differences, I've found at least one case of a "switch":

```
<  <message key="xmlui.Administrative.WithdrawnItems.title.item.dateissued">Umaknjeni vnosi po datumu izdaje</message>                                        
<  <message key="xmlui.Administrative.WithdrawnItems.trail.item.dateissued">Umaknjeni vnosi po datumu izdaje</message>                                        
<  <message key="xmlui.Administrative.WithdrawnItems.title.item.dateaccessioned">Umaknjeni vnosi po datumu vnosa</message>                                    
<  <message key="xmlui.Administrative.WithdrawnItems.trail.item.dateaccessioned">Umaknjeni vnosi po datumu vnosa</message>                                    
---                                                                                                                                                           
>  <message key="xmlui.Administrative.WithdrawnItems.title.item.dateissued">Umaknjeni vnosi po datumu vnosa</message>                                         
>  <message key="xmlui.Administrative.WithdrawnItems.trail.item.dateissued">Umaknjeni vnosi po datumu vnosa</message>                                         
>  <message key="xmlui.Administrative.WithdrawnItems.title.item.dateaccessioned">Umaknjeni vnosi po datumu izdaje</message>                                   
>  <message key="xmlui.Administrative.WithdrawnItems.trail.item.dateaccessioned">Umaknjeni vnosi po datumu izdaje</message> 

```

For the full diff (on fado):
```
$ diff -w /project/lindat-dspace/source/dspace/modules/xmlui/src/main/webapp/i18n/messages_sl.xml /project/lindat-dspace/tmp/messages_sl.xml
```

3. Some of the keys that weren't included had also not been translated before, so they remain in English (e.g., `<message key="xmlui.XMLWorkflow.default.reviewstep">Accept/Reject</message>`).

I wrote a little script which replaces (or adds) messages in one file with matching ones (via kay) in another. I'm attaching the output (as txt to make github happy) of running this on the current messages_sl.xml with the new one. Are we sure we want to activate this as is?
[messages_sl.txt](https://github.com/clarinsi/clarin-dspace/files/2609333/messages_sl.txt)

**Comment by cyplas** [comment]
As agreed (though a bit modified), I've assembled a new messages_sl.xml in several steps, and set a (temporary) source attribute as indicated:

1. Start with the English messages.template file (I had forgotten about this, this is actually the basis that lindat recommends, not the (slightly different) fusion of the 4 message files I previously used). (source = "en-template")
2. Overwrite messages with our English messages (from the 4 English message files). (source = "en-current")
3. If different, overwrite messages with those in our current messages_sl.xml. (source = "sl-current")
4. Overwrite messages with those in the last message file provided by Tomaz. (source = "sl-new")

I've redeployed on fado with the resultant merged messages file (which is therefore available at /project/lindat-dspace/source/dspace/modules/xmlui/src/main/webapp/i18n/messages_sl.xml). 

Tomaz, the next step is for you to provide me with translations for the messages that don't have source = "sl-new". That should get us almost there (almost because the message localisation system still has a few holes, such as "Collections in this community:" being hard-coded in community-list.xsl).

**Comment by TomazErjavec** [comment]
> Tomaz, the next step is for you to provide me with translations

Will do, everything set up for this work on fado.

**Comment by TomazErjavec** [comment]
The above has now been translated. The resultant file is on fado, 
/home/tomaz/LINDAT/Translated/messages_sl.xml

(note that the `@source` attributes are still present in the file)

**Comment by cyplas** [comment]
The new translations are now activated (on fado).

**Comment by TomazErjavec** [comment]
Thanks. There is one weird thing already on the home screen though, which makes me worried that maybe other messages are missing as well: in Slovene locale the message "Collections & Communities" is not translated, and if I look for this message in my "all_messages.xml" file, I can't find it (but I can find "Communities &amp; Collections", which is even weirder). 

Also, if I then click on this menu item, so https://beta.clarin.si/repository/xmlui/community-list most messages there are not translated either, eg. "Collections in this community:". However, in this case I can find the string in all_messages (key "xmlui.ArtifactBrowser.CommunityViewer.head_sub_collections") and this message has been translated ("Zbirke v tej skupnosti"). Not sure if this is the correct message/key though, as note that the eng message in the file is missing the final ":" which does appear in the browser.

Could you pls. check what is going on here?

**Comment by cyplas** [comment]
It seems that these are still hard-coded in certain files, such as a Navigation.java and community-list.xsl (try, for instance, `grep -r "Collections in this community" | grep -v /target/`). I think that (at least some of) these files have normal access to the message i18n system, so new keys could be added to messages and used in these files. But the first should maybe be that I ask Lindat, as this issue is not specific to our repo.

**Comment by cyplas** [comment]
Just discussed this with Ondrej. I will try to localise the static strings by turning them into (possibly new) message key references (although I'm unlikely to reliably find them all automatically). Then I can make a pull request upstream to lindat.

**Comment by cyplas** [comment]
> Just discussed this with Ondrej. I will try to localise the static strings by turning them into (possibly new) message key references (although I'm unlikely to reliably find them all automatically). Then I can make a pull request upstream to lindat.

I've now done this on fado for the static strings on the community list page (https://beta.clarin.si/repository/xmlui/community-list?locale-attribute=sl) and the communities link in the navigation menu. Tomaz, please check my translations.

As it would be very hard to systematically find all unlocalised strings, so I propose we do this manually and asymptotically: periodically look for and/or report on such strings in the interface, and create and use new message keys for them.

**Comment by TomazErjavec** [comment]
> Tomaz, please check my translations.

"Ni podskupnosti v ti skupnosti." should be "Ni podskupnosti v tej skupnosti." otherwise b.p.

**Comment by TomazErjavec** [comment]
> Tomaz, please check my translations.

"Ni podskupnosti v ti skupnosti." should be "Ni podskupnosti v tej skupnosti." otherwise b.p.

**Comment by cyplas** [comment]
> "Ni podskupnosti v ti skupnosti." should be "Ni podskupnosti v tej skupnosti." otherwise b.p.

Fixed.

I did a quick browse for unlocalised strings of all the main views under the main "Adminstrative" menu:

* Control Panel - all tabs (e.g., "Java Information")
* Access Control - People: "More information", all label info (e.g., "Can login")
* Statistics: everything (e.g., "General Overview")
* Curation Tasks: "Run all curation tasks at once" button, all curation tasks (e.g., "Summarise Bitstream Formats")
* Licences: all tabs (e.g., "All Licenses") and columns (e.g., "License Name")

So there's lots of stuff there, but I'm not sure that all of it makes sense to translate. Maybe the goal for now should be to make more consistent what is and what is not translated? To that end, I've now created keys for the local black sheep of "More information" ("Več informacij") and "Run all curation tasks at once" ("Poženi vse naloge hkrati").

**Comment by TomazErjavec** [comment]
> So there's lots of stuff there, but I'm not sure that all of it makes sense to translate. 

I agree. Esp. messages that are seen only by admins could easily be skipped.

**Comment by cyplas** [comment]
Ok, it looks like we're now done with this, given that we're not trying to localise all admin strings. Except for possible systematic improvements (e.g., "Ta vnos vsebuje X datotek(...)."), but let's create separate issue(s) for that, as it might be quite involved.

**Comment by cyplas** [comment]
Just to note, as Tomaz found, that there are still some non-admin unlocalised strings, but (if I'm not mistaken) they are all hard-coded, meaning not (yet) localisable in clarin-dspace in general. For example, https://github.com/ufal/clarin-dspace/blob/clarin/dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/eperson/LoginChooser.java#L197.
