### ISSUE TITLE
Can't download files while checking submission

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/clarin-dspace#33]
I've just noticed that when a submitted item is being checked you can't download the associated files. This happens both on production server and on beta. However, document preview works ok.
Below the stack trace for item "testo" on beta:

```
Cocoon stacktrace
Failed to process reader
context:/jndi:/localhost/repository/xmlui/sitemap.xmap - 309 : 78<map:read type="BitstreamReader">
context:/jndi:/localhost/repository/xmlui/sitemap.xmap - 299 : 68<map:select type="browser">
context:/jndi:/localhost/repository/xmlui/sitemap.xmap - 298 : 88<map:match type="request-parameter">
context:/jndi:/localhost/repository/xmlui/sitemap.xmap - 296 : 70<map:match>
```

**Comment by cyplas** [comment]
Where is testo on beta? I don't see it among published items nor among submissions nor via search.

Do you think this is a new bug? At first glance, I would guess that it's neither new nor clarin.si-specific, as the stacktrace refers to dspace-xmlui/src/main/webapp/sitemap.xmap, which hasn't changed since 2017 and there's no difference between clarin and si-master versions.

**Comment by TomazErjavec** [comment]
> Where is testo on beta?

Sorry, this is an entry that I started entering, so, of course, you cannot see it. I suggest you make an entry of your own with a file attached, and then test.

> Do you think this is a new bug?

I do, or at least it laid dormant for some reason. I often (but, alas, not always) check also the files submitted, so I would've noticed it, if it existed before.

>  I would guess that it's neither new nor clarin.si-specific

This souds strange. Could it not be that something upstream causes it? No idea though, except that the bug is real and makes it impossible to check deposited files by the editor.

**Comment by cyplas** [comment]
> Could it not be that something upstream causes it?

It certainly could be, I was just giving a first superficial impression based on the file referred to in the stacktrace.

**Comment by cyplas** [comment]
Ok, I think I've replicated this, but want to make sure we're talking about the same thing:

1. Logged in (as admin).
2. Started a new submission.
3. At Step 4 (Upload), uploaded a trivial text file. 
4. Previewed it successfully (in the File column).
5. Continued with all the steps through 8.
6. Save & Exit.
7. Save it, I'll work on it later.
8. Click on the submission (among Unfinished submissions).
9. Download file (fail, with your cocoon stacktrace and the java stacktrace attached
[java.txt](https://github.com/clarinsi/clarin-dspace/files/3896224/java.txt)
10. Resume.
11. Complete submission.
12. Click on the submission (now among Archived submissions).
13. Download file (success).

Does this match your experience?

**Comment by TomazErjavec** [comment]
Yes, this is it, except that fail also happens when I, as the editor, am checking a completed submission. So, it seems that as long a repo entry is in the submission process, the files cannot be downaloaded, regardles of whether it is by the submittor or by the editor.

**Comment by cyplas** [comment]
> Yes, this is it, except that fail also happens when I, as the editor, am checking a completed submission. So, it seems that as long a repo entry is in the submission process, the files cannot be downaloaded, regardles of whether it is by the submittor or by the editor.

Either I'm not understanding you right or we are having different experiences. My test scenario identified a difference between what I would call not-completed submissions (failure at step 9) and completed submissions (success at step 13). When you say "a completed submission", if you mean the same thing as me, then I wonder why you cannot download while I can. Are you able to download it as submitter but not as editor?

**Comment by TomazErjavec** [comment]
For me "Completed submission" is only when the Editor has checked the submission and approved it, sorry for the terminology breakdown. I though it was the same for you, otherwise, I don't think you can see it in the Archived submissions, and much less in the New submission on the top page. And I can see your two tests.

So, maybe you should change the above to

Complete submission.
Log in as the editor of the repository and take the completed submission for checking
Download file (fail, again)
Approve the submission
Click on the submission (now among New submission
Download file (success).

I just tried the above with "testo", and it is as written, ie. the editor cannot download it.
However, on beta there was another, very old submission, waiting to be approved. And there the download works, so, another reason to think this is a new bug.

**Comment by cyplas** [comment]
Ondrej pointed me to https://github.com/ufal/clarin-dspace/pull/902/commits/df3a82e085d7d499ee52a93a8a5258a45e4c5b0b. This is on the clarin-dev branch, but I cherry-picked the commit onto si-master (on fado for now), and I can now access the file at step 9 of https://github.com/clarinsi/clarin-dspace/issues/33#issuecomment-559018845. Can you test your way and confirm?

**Comment by TomazErjavec** [comment]
Great, I checked on fado, and it works, both for the submitter and the editor. So, pls. instal in fido as well.

**Comment by cyplas** [comment]
> pls. instal in fido as well.

Done.

**Comment by cyplas** [comment]
@TomazErjavec I'll leave a final pre-issue-close fido fest to you.

**Comment by TomazErjavec** [comment]
Looks like everything is ok now!
