### ISSUE TITLE
OpenAIRE not harvesting metadata

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/clarin-dspace#38]
If you click on "Research Data" at https://www.openaire.eu/search/dataprovider?datasourceId=re3data_____::fe0d76581a60e1287a93e2ed2cb29339 you see that the titles, descriptions etc. of resources are not harvested (correctly).  The Czech repo doesn't have this problem: https://explore.openaire.eu/search/dataprovider?datasourceId=re3data_____::a507cdacc5bbcc08761c92185dee5cab

This might be fall-out from the fact that we are 593 commits behind ufal:clarin, but maybe not, so better have an issue on this problem.

**Comment by TomazErjavec** [comment]
Just to note that this should be probably cross-referenced to #13. Also assigning @cyplas to this.

**Comment by cyplas** [comment]
Ondrej says this has been fixed (https://github.com/ufal/clarin-dspace/pull/947) and should be included in the next release.
If it seems urgent, I can try to incorporate the fix sooner, but I would prefer not to do that, as I would have to cherry-pick commits, which risks breaking other functionality.

**Comment by TomazErjavec** [comment]
> Ondrej says this has been fixed (ufal#947) and should be included in the next release.

That is good news - but it's funny, because last time I checked it actually worked for UFAL, but not for us. 

> If it seems urgent, I can try to incorporate the fix sooner, but I would prefer not to do that, as I would have to cherry-pick commits, which risks breaking other functionality.

No, not so urgent - we might as well wait for the official release.

Let's leave this issue open until it is fixed.

**Comment by cyplas** [comment]
> That is good news - but it's funny, because last time I checked it actually worked for UFAL, but not for us.

That may well be, as they may well be deploying from a dev branch.

**Comment by TomazErjavec** [comment]
The problem seems to have been solved with the new release, (cf. eg. https://explore.openaire.eu/search/dataprovider?datasourceId=re3data_____::fe0d76581a60e1287a93e2ed2cb29339) so closing.
