### ISSUE TITLE
"Your session has expired" error

### ISSUE THREAD

**Issue by katjameden** [clarinsi/clarin-dspace#39]
After a successful login on the CLARIN.SI beta repository with local authentication process and a short amount of time spent adding a new test submission (around 1-3 min), I continuously run into the "Your Session has expired" error. This error occurs every time, no matter what task I am performing while editing a submission. I am adding a screenshot of the entire error log. 

[beta_clarin.si_errorLog.pdf](https://github.com/clarinsi/clarin-dspace/files/5707819/beta_clarin.si_errorLog.pdf)

**Comment by cyplas** [comment]
Hmm, this error log looks cryptic and I can't reproduce the error (e.g., while testing https://redmine.cjvt.si/issues/1697). Katja, could you post the timestamp the next time you have this problem, so I can dig around the logs a bit more?

**Comment by cyplas** [comment]
Katja, is this problem still persisting?

**Comment by katjameden** [comment]
> Katja, is this problem still persisting?

Hi Cyprian, so sorry for my late response. I tested this error persistently and I think it has to do with an unstable wifi connection I have in my INZ office, as I am able to do my work from home (or was able to do that from the IJS office) without any problems. I handed out a purchase order to get an adapter for mac, so that I am able to get a stable connection via ethernet cable. 

Just in case this is not it, I was able to reproduce the error on 11:01 (3.2.2021) on the CLARIN.SI beta repository.

**Comment by cyplas** [comment]
> I tested this error persistently and I think it has to do with an unstable wifi connection I have in my INZ office, as I am able to do my work from home (or was able to do that from the IJS office) without any problems. I handed out a purchase order to get an adapter for mac, so that I am able to get a stable connection via ethernet cable.
> 
> Just in case this is not it, I was able to reproduce the error on 11:01 (3.2.2021) on the CLARIN.SI beta repository.

I took a look in the logs. I didn't find anything obviously unusual in the authentication logs. In the generic dspace logs, there seems to be a correlation between your sessions and xoai errors (https://github.com/clarinsi/clarin-dspace/issues/5), but that might just be because you're testing submissions.

So, hmm, yes, let's wait and see if your new adapter helps. Otherwise, we can try to see over skype some time if the problem occurs even if I login as you (given your credentials).

**Comment by katjameden** [comment]
Hi, just a quick update on the issue. 
I now have a stable connection (ethernet cable), the error is gone and I am able to work on the CLARIN.SI repository with no problems (on beta and on alpha as well).

**Comment by TomazErjavec** [comment]
OK, great! So, we can close.
