### ISSUE TITLE
Health check not working: no connection slots

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/clarin-dspace#41]
For two weeks in a row, the CLARIN.SI: Repository healthcheck is not working, i.e. it reports ad nauseam the following:
```
Exception occurred when processing report - java.lang.IllegalStateException: org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections
```
and no useful healthcheck is performed. I tried running curation checks from the repo, and those worked fine.
No idea what is happening, but given that this now occured twice, it would be good if @cyplas could investigate.

**Comment by cyplas** [comment]
I don't know what this was about, but it hasn't been occurring for a while, closing.
